FROM docker.io/postgres:latest

LABEL Leonardo Viana <leonardoviana00@hotmail.com>

ENV POSTGRES_PASSWORD=apirest
ENV POSTGRES_DB=apirest
ENV POSTGRES_USER=apirest


VOLUME [ "/var/lib/postgresql/data" ]


EXPOSE 5432